#ifndef DS5_BRIDGE_WEB_PAGE_8BITDO_H
#define DS5_BRIDGE_WEB_PAGE_8BITDO_H

// Minimal brutalist web page for the 8BitDo bridge config UI.
// Header is embedded so httpd serves it without fs_open_custom overhead.
static const char WEB_PAGE[] =
"HTTP/1.1 200 OK\r\n"
"Content-Type: text/html; charset=utf-8\r\n"
"Cache-Control: no-store\r\n"
"Connection: close\r\n\r\n"
"<!doctype html><html><head><meta charset=utf-8><meta name=viewport content=\"width=device-width,initial-scale=1\">"
"<title>8BitDo Bridge</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font:16px/1.5 monospace;background:#111;color:#eee;padding:2rem}"
"h1{font-size:1.5rem;border-bottom:2px solid #eee;padding-bottom:.5rem;margin-bottom:1.5rem}"
".card{background:#222;border:1px solid #444;padding:1.5rem;margin-bottom:1rem}"
"label{display:block;margin-bottom:.5rem;font-weight:bold}"
"input[type=text]{width:100%;padding:.5rem;background:#000;border:1px solid #666;color:#eee;font:inherit;margin-bottom:1rem}"
"button{padding:.5rem 1.5rem;background:#eee;color:#111;border:none;font:inherit;cursor:pointer;margin-right:.5rem}"
"button:hover{background:#ccc}"
".status{padding:.5rem;margin-top:1rem;border:1px solid #666}"
"</style></head><body>"
"<h1>8BitDo Bridge</h1>"
"<div class=card><label>Controller</label><div id=st class=status>Checking...</div></div>"
"<div class=card><label>WoL MAC 1</label><input type=text id=wol1 maxlength=12 placeholder=AABBCCDDEEFF>"
"<label>WoL MAC 2</label><input type=text id=wol2 maxlength=12 placeholder=AABBCCDDEEFF>"
"<button onclick=save()>Save</button><button onclick=wake()>Wake</button></div>"
"<div class=card><label>TV ADB IP</label><input type=text id=tvip placeholder=192.168.1.100>"
"<label><input type=checkbox id=tvadb> Enable TV Control</label><br>"
"<label><input type=checkbox id=tvsleep> Sleep on Suspend</label><br>"
"<label><input type=checkbox id=tvwake> Input on Wake</label><br>"
"<button onclick=save()>Save</button></div>"
"<div class=card><label>Hostname</label><input type=text id=host maxlength=10 placeholder=ds5>"
"<button onclick=save()>Save</button></div>"
"<script>"
"function load(){fetch('/api/config').then(r=>r.json()).then(d=>{"
"document.getElementById('wol1').value=d.wol_target_mac||'';"
"document.getElementById('wol2').value=d.wol_target_mac2||'';"
"document.getElementById('tvip').value=d.tv_server_ip||'';"
"document.getElementById('tvadb').checked=!!d.tv_adb_enabled;"
"document.getElementById('tvsleep').checked=!!d.tv_sleep_on_suspend;"
"document.getElementById('tvwake').checked=!!d.tv_input_on_wake;"
"document.getElementById('host').value=d.hostname||'';"
"})}"
"function status(){fetch('/api/status').then(r=>r.json()).then(d=>{"
"document.getElementById('st').textContent=d.connected?'Connected':'Disconnected';"
"})}"
"function save(){var b='wol_target_mac='+document.getElementById('wol1').value"
"+'&wol_target_mac2='+document.getElementById('wol2').value"
"+'&tv_server_ip='+encodeURIComponent(document.getElementById('tvip').value)"
"+'&tv_adb_enabled='+(document.getElementById('tvadb').checked?1:0)"
"+'&tv_sleep_on_suspend='+(document.getElementById('tvsleep').checked?1:0)"
"+'&tv_input_on_wake='+(document.getElementById('tvwake').checked?1:0)"
"+'&hostname='+encodeURIComponent(document.getElementById('host').value);"
"fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b}).then(load)}"
"function wake(){fetch('/api/wol',{method:'POST',body:'action=wake'})}"
"load();status();setInterval(status,5000);"
"</script></body></html>";

#endif // DS5_BRIDGE_WEB_PAGE_8BITDO_H
